import './globals.css'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth/next'
import { Inter } from 'next/font/google'
import { authOptions } from './auth'
import { Providers } from './providers'
import { SignInTrigger } from './sign-in-trigger'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
	const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <SignInTrigger>
            {children}
          </SignInTrigger>
        </Providers>
      </body>
    </html>
  )
}
